// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXNsPF1ZSnbrm7lbx-QaIGaCdg1zzdjlo',
    appId: '1:936328801204:web:707f5065f911aa4090e0e1',
    messagingSenderId: '936328801204',
    projectId: 'flutter-gregtext-game',
    authDomain: 'flutter-gregtext-game.firebaseapp.com',
    storageBucket: 'flutter-gregtext-game.firebasestorage.app',
    measurementId: 'G-23FYHQ9PH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP9yJMdjeT6csmo7B_eRcmflakUHyzAiA',
    appId: '1:936328801204:android:41ec39c3159b7ae390e0e1',
    messagingSenderId: '936328801204',
    projectId: 'flutter-gregtext-game',
    storageBucket: 'flutter-gregtext-game.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRox0p80VEy9ws_Q0d8FrwOtX8kQXmxxs',
    appId: '1:936328801204:ios:1811b22f57a3d52f90e0e1',
    messagingSenderId: '936328801204',
    projectId: 'flutter-gregtext-game',
    storageBucket: 'flutter-gregtext-game.firebasestorage.app',
    iosBundleId: 'com.example.flutterGregtextGame',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRox0p80VEy9ws_Q0d8FrwOtX8kQXmxxs',
    appId: '1:936328801204:ios:1811b22f57a3d52f90e0e1',
    messagingSenderId: '936328801204',
    projectId: 'flutter-gregtext-game',
    storageBucket: 'flutter-gregtext-game.firebasestorage.app',
    iosBundleId: 'com.example.flutterGregtextGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXNsPF1ZSnbrm7lbx-QaIGaCdg1zzdjlo',
    appId: '1:936328801204:web:93200805d937c08590e0e1',
    messagingSenderId: '936328801204',
    projectId: 'flutter-gregtext-game',
    authDomain: 'flutter-gregtext-game.firebaseapp.com',
    storageBucket: 'flutter-gregtext-game.firebasestorage.app',
    measurementId: 'G-JLLR69ZLTH',
  );
}
